name: Generate snake

on:
  schedule:
    - cron: "0 0 * * *" # Run once a day (UTC)
  workflow_dispatch: # Allow manual runs
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # Generate snake files
      - name: Generate snake SVGs
        uses: Platane/snk@v3
        with:
          github_user_name: Tharaka4452
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      # Publish to output branch
      - name: Push snake to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
